# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LyVygrW7uFUxQEYLwVAsHH0HdzXDv4Y0
"""

# 1. 라이브러리 설치 및 로드
!pip install -q gradio

import gradio as gr

# --- 대폭 확장된 식품 데이터베이스 및 영양소 밀도 (100g당 함량) ---

CARB_DB = [
    # 초록불 (추천)
    {"name": "현미밥", "density": 33, "desc": "식이섬유가 풍부해 혈당 스파이크를 방지하고 콜레스테롤 배출을 돕습니다.", "emoji": "🟢"},
    {"name": "잡곡밥 (귀리/보리 등)", "density": 30, "desc": "베타글루칸이 혈중 콜레스테롤을 낮추고 인슐린 감수성을 높입니다.", "emoji": "🟢"},
    {"name": "오트밀 (조리 전)", "density": 65, "desc": "대표적인 수용성 식이섬유 식품으로 혈당과 지질 대사에 모두 좋습니다.", "emoji": "🟢"},
    {"name": "통밀빵 / 호밀빵", "density": 45, "desc": "정제되지 않은 곡물빵으로 일반 식빵보다 소화 흡수가 느려 안전합니다.", "emoji": "🟢"},
    {"name": "메밀면 (메밀 80% 이상)", "density": 70, "desc": "루틴 성분이 혈관을 튼튼하게 하고 혈당 지수(GI)가 낮습니다.", "emoji": "🟢"},
    {"name": "곤약밥", "density": 12, "desc": "탄수화물 밀도가 극도로 낮아 포만감 대비 혈당 영향이 거의 없습니다.", "emoji": "🟢"},

    # 노란불 (주의)
    {"name": "찐 고구마", "density": 32, "desc": "좋은 탄수화물이지만 구우면 당도가 급증하므로 꼭 '찐' 상태로 드세요.", "emoji": "🟡"},
    {"name": "찐 감자", "density": 17, "desc": "포만감은 좋으나 GI 지수가 다소 높은 편이므로 권장량을 준수하세요.", "emoji": "🟡"},
    {"name": "단호박", "density": 15, "desc": "식이섬유는 풍부하나 많이 먹으면 탄수화물 총량이 늘어나므로 주의합니다.", "emoji": "🟡"},
    {"name": "바나나", "density": 23, "desc": "과당과 탄수화물 밀도가 높으므로 한 번에 1개 이하로 제한합니다.", "emoji": "🟡"},
    {"name": "사과", "density": 14, "desc": "펙틴이 콜레스테롤을 낮춰 고지혈증엔 좋으나 당뇨 환자는 반 쪽만 권장합니다.", "emoji": "🟡"},

    # 빨간불 (제한)
    {"name": "흰쌀밥", "density": 33, "desc": "정제 곡물로 혈당을 매우 빠르게 올리며 체내 중성지방을 축적시킵니다.", "emoji": "🔴"},
    {"name": "라면 / 짜장면 (밀가루면)", "density": 65, "desc": "정제 밀가루와 높은 나트륨, 포화지방이 결합하여 매우 위험합니다.", "emoji": "🔴"},
    {"name": "가래떡 / 떡볶이 떡", "density": 50, "desc": "곡물을 압착하여 탄수화물 밀도가 극도로 높아 혈당 스파이크를 유발합니다.", "emoji": "🔴"},
    {"name": "단팥빵 / 케이크 (빵류)", "density": 55, "desc": "설탕과 정제 밀가루, 버터의 조합으로 당뇨와 고지혈증 최악의 식품입니다.", "emoji": "🔴"},
    {"name": "콜라 / 가당 주스", "density": 11, "desc": "액상과당은 인슐린 저항성을 급격히 악화시키고 고지혈증을 직접 유발합니다.", "emoji": "🔴"}
]

PROTEIN_DB = [
    # 초록불 (추천)
    {"name": "닭가슴살 (기름 없는 부위)", "density": 23, "desc": "기름기가 거의 없고 단백질 밀도가 높아 고지혈증, 당뇨에 가장 안전합니다.", "emoji": "🟢"},
    {"name": "두부 / 연두부", "density": 9, "desc": "식물성 단백질로 이소플라본 성분이 LDL 콜레스테롤 수치를 낮춰줍니다.", "emoji": "🟢"},
    {"name": "고등어 / 삼치 / 연어", "density": 20, "desc": "오메가-3 지방산이 풍부하여 혈중 중성지방 수치를 차단하고 낮춰줍니다.", "emoji": "🟢"},
    {"name": "오징어 / 문어 (숙회)", "density": 18, "desc": "지방이 거의 없고 타우린이 풍부해 피로 해소와 혈관 건강에 좋습니다.", "emoji": "🟢"},
    {"name": "소고기 우둔살 / 홍두깨살", "density": 22, "desc": "붉은 고기 중 지방이 가장 적은 부위로 기름기 없는 단백질 보충에 좋습니다.", "emoji": "🟢"},
    {"name": "계란 흰자", "density": 11, "desc": "지방과 콜레스테롤이 전혀 없는 순수 단백질원입니다.", "emoji": "🟢"},

    # 노란불 (주의)
    {"name": "계란 (전란)", "density": 12, "desc": "완전식품이나 고지혈증이 있다면 노른자는 하루 1개 이하로 제한을 권장합니다.", "emoji": "🟡"},
    {"name": "돼지 목살 (구이)", "density": 20, "desc": "삼겹살보다는 안전하지만 포화지방이 있으므로 기름진 부위는 떼고 드세요.", "emoji": "🟡"},
    {"name": "소고기 등심", "density": 19, "desc": "마블링(지방)이 포함되어 있으므로 과도한 섭취는 주의가 필요합니다.", "emoji": "🟡"},

    # 빨간불 (제한)
    {"name": "돼지 삼겹살", "density": 17, "desc": "포화지방 비율이 너무 높아 고지혈증 환자의 혈관을 막는 주원인이 됩니다.", "emoji": "🔴"},
    {"name": "소고기 차돌박이", "density": 16, "desc": "고소한 맛만큼 포화지방이 꽉 차 있어 LDL 콜레스테롤을 폭등시킵니다.", "emoji": "🔴"},
    {"name": "햄 / 소시지 (가공육)", "density": 15, "desc": "발색제와 나트륨, 포화지방이 많아 심혈관 질환 위험도를 대폭 높입니다.", "emoji": "🔴"}
]

FAT_DB = [
    # 초록불 (추천)
    {"name": "올리브유 (엑스트라버진)", "density": 100, "desc": "올레인산이 풍부해 유해 콜레스테롤(LDL)을 낮춰줍니다. (1스푼=약 8g)", "emoji": "🟢"},
    {"name": "들기름", "density": 100, "desc": "식물성 오메가-3(알파리놀렌산)가 매우 풍부해 혈관 염증을 억제합니다. (1스푼=약 8g)", "emoji": "🟢"},
    {"name": "아보카도 오일", "density": 100, "desc": "혈관을 깨끗하게 하는 불포화지방산 함량이 매우 높습니다. (1스푼=약 8g)", "emoji": "🟢"},
    {"name": "생 아보카도", "density": 15, "desc": "숲속의 버터로 불리며, 건강한 지방과 믾은 식이섬유를 동시에 섭취할 수 있습니다.", "emoji": "🟢"},

    # 노란불 (주의)
    {"name": "아몬드", "density": 50, "desc": "불포화지방이 많으나 칼로리가 높으므로 한 번에 한 줌 미만으로 제한합니다.", "emoji": "🟡"},
    {"name": "호두", "density": 65, "desc": "뇌와 혈관에 좋지만 지방 밀도가 높아 과다 섭취 시 체중이 증가할 수 있습니다.", "emoji": "🟡"},
    {"name": "땅콩 버터 (무가당)", "density": 50, "desc": "당류가 없는 순수 땅콩버터는 좋은 지방원이지만 하루 1스푼 이내로 제한합니다.", "emoji": "🟡"},

    # 빨간불 (제한)
    {"name": "버터 (동물성)", "density": 81, "desc": "포화지방 덩어리로 혈관 벽에 콜레스테롤을 축적시키는 주범입니다.", "emoji": "🔴"},
    {"name": "마가린 / 쇼트닝", "density": 80, "desc": "인공적으로 만든 트랜스지방이 포함되어 혈관 건강에 치명적입니다.", "emoji": "🔴"},
    {"name": "돼지기름 (라드)", "density": 100, "desc": "포화지방산 혈중 농도를 높여 피를 끈적하게 만들고 고지혈증을 악화시킵니다.", "emoji": "🔴"}
]

# 2. 맞춤형 영양소 연산 및 실물 중량 환산 함수
def predict_diet_v4(disease, gender, age, height, weight, activity, goal, medication):
    if gender == "남성":
        bmr = 66.47 + (13.75 * weight) + (5 * height) - (6.76 * age)
    else:
        bmr = 655.1 + (9.56 * weight) + (1.85 * height) - (4.68 * age)

    activity_map = {"거의 활동 안 함 (주로 앉아서 생활)": 1.2, "가벼운 활동 (주 1~3회 가벼운 운동)": 1.375, "보통 활동 (주 3~5회 적당한 운동)": 1.55, "적극적 활동 (매일 강도 높은 운동)": 1.725}
    tdee = bmr * activity_map.get(activity, 1.2)

    target_cal = tdee - 400 if goal == "체중 감량 (다이어트)" else (tdee + 300 if goal == "체중 증량" else tdee)

    if "당뇨" in disease or "둘 다" in disease:
        carb_p, pro_p, fat_p = 0.45, 0.20, 0.35
    else:
        carb_p, pro_p, fat_p = 0.50, 0.20, 0.30

    meal_carb = ((target_cal * carb_p) / 4) / 3
    meal_protein = ((target_cal * pro_p) / 4) / 3
    meal_fat = ((target_cal * fat_p) / 9) / 3

    result_html = f"""
    <div style='font-family: sans-serif; padding: 20px; border: 2px solid #2e7d32; border-radius: 10px; background-color: #fefefe;'>
        <h2 style='color: #2e7d32; margin-top: 0; border-bottom: 2px solid #2e7d32; padding-bottom: 8px;'>📊 한 끼 맞춤형 정밀 식단 처방전 (확장판)</h2>
        <p style='color: #666; font-size: 0.9em;'>추천 하루 권장 칼로리: <b>{int(target_cal)} kcal</b> | 선택 모드: <b>{disease}</b></p>

        <div style='display: flex; gap: 10px; margin-bottom: 20px;'>
            <div style='flex: 1; background-color: #e8f5e9; padding: 10px; border-radius: 6px; text-align: center;'>
                <span style='font-size: 0.85em; color: #2e7d32;'>🥖 권장 탄수화물</span><br>
                <span style='font-size: 1.3em; font-weight: bold; color: #1b5e20;'>{int(meal_carb)}g</span>
            </div>
            <div style='flex: 1; background-color: #e3f2fd; padding: 10px; border-radius: 6px; text-align: center;'>
                <span style='font-size: 0.85em; color: #1565c0;'>🍗 권장 단백질</span><br>
                <span style='font-size: 1.3em; font-weight: bold; color: #0d47a1;'>{int(meal_protein)}g</span>
            </div>
            <div style='flex: 1; background-color: #fff3e0; padding: 10px; border-radius: 6px; text-align: center;'>
                <span style='font-size: 0.85em; color: #e65100;'>🥑 권장 지방</span><br>
                <span style='font-size: 1.3em; font-weight: bold; color: #e65100;'>{int(meal_fat)}g</span>
            </div>
        </div>
    """

    if medication == "예 (인슐린 또는 특정 혈당강하제 복용 중)" and ("당뇨" in disease or "둘 다" in disease):
        result_html += "<div style='background-color: #ffebee; padding: 10px; border-radius: 5px; color: #c62828; margin-bottom:20px; font-size:0.9em;'>⚠️ <b>저혈당 주의:</b> 약물 처방 환자이므로 탄수화물을 굶지 마시고 안내된 정량을 섭취하세요.</div>"

    def generate_table(title, db, target_g, db_type):
        table_html = f"""
        <div style='margin-bottom: 20px; border: 1px solid #ddd; border-radius: 6px; overflow: hidden;'>
            <div style='background-color: #f5f5f5; padding: 8px 12px; font-weight: bold; border-bottom: 1px solid #ddd;'>{title}</div>
            <table style='width: 100%; border-collapse: collapse; background: white; font-size: 0.9em; text-align: left;'>
                <tr style='background-color:#fafafa; border-bottom: 1px solid #eee;'>
                    <th style='padding:8px; width: 30%;'>식품명</th>
                    <th style='padding:8px; color:#007bff; width: 30%;'>실제 추천 섭취량</th>
                    <th style='padding:8px; width: 40%;'>환자 식단 안내</th>
                </tr>
        """
        for item in db:
            real_weight = int((target_g / item["density"]) * 100)

            # 단위 세분화 출력 처리
            if db_type == "fat" and item["density"] == 100:  # 오일류
                quantity_display = f"약 {real_weight}g (약 {round(real_weight/8, 1)} 스푼)"
            elif item["name"] == "아몬드":
                quantity_display = f"약 {real_weight}g (약 {int(real_weight/1.2)} 알)"
            elif item["name"] == "호두":
                quantity_display = f"약 {real_weight}g (약 {int(real_weight/3.5)} 알)"
            elif item["name"] == "계란 (전란)":
                quantity_display = f"약 {real_weight}g (중란 약 {int(real_weight/50)} 개)"
            elif item["name"] == "계란 흰자":
                quantity_display = f"약 {real_weight}g (란백 약 {int(real_weight/30)} 개분)"
            else:
                quantity_display = f"약 {real_weight}g"

            desc = item["desc"]
            if "둘 다" in disease and item["emoji"] == "🔴":
                desc = "🚨 <b>[복합 환자 위험]</b> 당뇨와 고지혈 혈관 합병증을 유발하므로 절대 기피대상입니다."

            table_html += f"""
                <tr style='border-bottom: 1px solid #eee;'>
                    <td style='padding:8px; font-weight:bold;'>{item["emoji"]} {item["name"]}</td>
                    <td style='padding:8px; color:#007bff; font-weight:bold;'>{quantity_display}</td>
                    <td style='padding:8px; color:#555; font-size:0.95em;'>{desc}</td>
                </tr>
            """
        table_html += "</table></div>"
        return table_html

    result_html += generate_table("🍞 1. 탄수화물 식품 리스트 (목표: " + str(int(meal_carb)) + "g 충족)", CARB_DB, meal_carb, "carb")
    result_html += generate_table("🍗 2. 단백질 식품 리스트 (목표: " + str(int(meal_protein)) + "g 충족)", PROTEIN_DB, meal_protein, "protein")
    result_html += generate_table("🥑 3. 지방 식품 리스트 (목표: " + str(int(meal_fat)) + "g 충족)", FAT_DB, meal_fat, "fat")

    result_html += "</div>"
    return result_html

# 3. Gradio 인터페이스 구성
with gr.Blocks(theme=gr.themes.Soft(primary_hue="green")) as demo: # Moved theme parameter back to gr.Blocks
    gr.Markdown("# 🩺 스마트 맞춤형 탄·단·지 정밀 식단 보조 서비스 (대용량 내장 DB)")
    gr.Markdown("신체 조건을 입력하면 **탄수화물 16종, 단백질 12종, 지방 10종**의 실제 음식 무게를 계산")

    with gr.Row():
        with gr.Column(scale=1):
            disease = gr.Radio(["당뇨 환자", "고지혈증 환자", "둘 다 앓고 있음 (당뇨 + 고지혈증)"], label="1. 관리 중인 질환 상태")
            gender = gr.Radio(["남성", "여성"], label="2. 성별")
            age = gr.Slider(minimum=10, maximum=100, value=50, step=1, label="3. 나이 (세)")
            height = gr.Slider(minimum=130, maximum=200, value=170, step=1, label="4. 키 (cm)")
            weight = gr.Slider(minimum=30, maximum=130, value=65, step=1, label="5. 몸무게 (kg)")
            activity = gr.Dropdown(["거의 활동 안 함 (주로 앉아서 생활)", "가벼운 활동 (주 1~3회 가벼운 운동)", "보통 활동 (주 3~5회 적당한 운동)", "적극적 활동 (매일 강도 높은 운동)"], value="거의 활동 안 함 (주로 앉아서 생활)", label="6. 평소 활동량")
            goal = gr.Dropdown(["현재 체중 유지", "체중 감량 (다이어트)", "체중 증량"], value="현재 체중 유지", label="7. 체중 관리 목표")
            medication = gr.Radio(["아니오 (복용 안 함 / 해당 없음)", "예 (인슐린 또는 특정 혈당강하제 복용 중)"], value="아니오 (복용 안 함 / 해당 없음)", label="8. 특정 당뇨약/인슐린 여부")

            btn = gr.Button("내 맞춤형 전체 식단 조회하기 🚀", variant="primary")

        with gr.Column(scale=1):
            output = gr.HTML(label="식단 분석 보고서")

    btn.click(predict_diet_v4, inputs=[disease, gender, age, height, weight, activity, goal, medication], outputs=output)

# 4. 공유 가능한 웹 링크 생성 활성화
demo.launch(share=True, debug=True) # Removed theme parameter from demo.launch()